services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tutoring
      - SPRING_DATASOURCE_USERNAME=dgasi
      - SPRING_DATASOURCE_PASSWORD=admin

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tutoring
      POSTGRES_USER: dgasi
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"